# Generated by Django 4.1.3 on 2022-11-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='select_musics',
            field=models.ManyToManyField(related_name='select_musics_set', to='playlist.music'),
        ),
    ]
