# Generated by Django 4.1.3 on 2022-11-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlist_select_musics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='music',
        ),
    ]
